SELECT E.ID, COALESCE(T.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E -- 왼쪽 테이블
LEFT JOIN
		(SELECT PARENT_ID, COUNT(ID) AS CHILD_COUNT
		    FROM ECOLI_DATA
			WHERE PARENT_ID IS NOT NULL
			GROUP BY PARENT_ID) AS T  -- 오른쪽 테이블
ON E.ID = T.PARENT_ID	
ORDER BY E.ID ASC