SELECT ID,
		CASE
				WHEN T2.QUARTILE = 1 THEN 'CRITICAL'
				WHEN T2.QUARTILE = 2 THEN 'HIGH'
				WHEN T2.QUARTILE = 3 THEN 'MEDIUM'
				WHEN T2.QUARTILE = 4 THEN 'LOW'
		END AS COLONY_NAME
FROM
		(SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTILE
		FROM ECOLI_DATA) AS T2
ORDER BY ID ASC