SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM
(
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE IN ("Intact Male", "Intact Female")
) AS I
JOIN 
(
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME IN ("Spayed Female", "Neutered Male")
) AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY I.ANIMAL_ID
