WITH RECURSIVE ECOLI_GENERATION AS (
	-- 1. 1세대 정의
	SELECT ID, PARENT_ID, 1 AS GENERATION
	FROM ECOLI_DATA
	WHERE PARENT_ID IS NULL
	
	UNION ALL
	
	-- 2. 재귀 멤버
	SELECT E.ID, E.PARENT_ID, G.GENERATION + 1 AS GENERATION
	FROM ECOLI_DATA AS E
	JOIN ECOLI_GENERATION AS G ON E.PARENT_ID = G.ID
)

SELECT COUNT(T1.ID) AS COUNT, T1.GENERATION
FROM ECOLI_GENERATION AS T1
LEFT JOIN ECOLI_DATA AS T2
ON T1.ID = T2.PARENT_ID
WHERE T2.ID IS NULL
GROUP BY T1.GENERATION
ORDER BY T1.GENERATION ASC