# SELECT SUM(TOTAL_ORDER), FLAVOR
# FROM JULY
# GROUP BY FLAVOR

SELECT H.FLAVOR
FROM FIRST_HALF AS H
JOIN 
    (
        SELECT SUM(TOTAL_ORDER) AS TOTAL_ORDER, FLAVOR
        FROM JULY
        GROUP BY FLAVOR
    ) AS J
ON H.FLAVOR = J.FLAVOR
ORDER BY H.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3