SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT AS P
JOIN APPOINTMENT AS A
    ON A.PT_NO = P.PT_NO
JOIN DOCTOR AS D
    ON D.DR_ID = A.MDDR_ID
WHERE D.MCDP_CD = 'CS' AND DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND A.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC