SELECT S.USER_ID, U.NICKNAME, S.TOTAL_SALES
FROM USED_GOODS_USER AS U
JOIN
(
    SELECT WRITER_ID AS USER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) AS S
ON S.USER_ID = U.USER_ID
ORDER BY S.TOTAL_SALES ASC