SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS P
JOIN 
(
    SELECT MEMBER_ID, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
    FROM REST_REVIEW
    WHERE MEMBER_ID IN (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING COUNT(*) = (
            SELECT COUNT(*)
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(*) DESC
            LIMIT 1    
        )
    )
) AS R
ON P.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC